import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import QueryProvider from '../providers/QueryProvider';
import AuthProvider from '../providers/AuthProvider';
import { albertSans, notoSans } from '../lib/fonts';
import Navigation from '../components/Navigation';
import '../styles/global.css';

export const metadata: Metadata = {
  title: 'Welcome to nx-react-monorepo',
  description: 'Generated by create-nx-workspace',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" className={`${notoSans.className} ${albertSans.variable}`}>
      <body>
        <AuthProvider>
          <QueryProvider>
            <header className="bg-gray-800">
              <Navigation />
            </header>
            <main>{children}</main>
            <ReactQueryDevtools initialIsOpen={false} />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
