name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn nx-cloud start-ci-run --stop-agents-after="e2e-ci"
        continue-on-error: true
      - uses: nrwl/nx-set-shas@v4
      - run: yarn nx-cloud record -- nx format:check
      - run: yarn nx affected -t lint build
      # - run: yarn nx affected -t lint test build
      # - run: yarn nx affected -t e2e-ci
